language: android
android:
   components:
   - tools
   - tools
   - platform-tools
   - android-25
   - build-tools-25.0.2
   - extra

jdk: oraclejdk8

sudo: required

script:
  - ./gradlew clean buildDebuggingApp

after_success:
  # Upload code coverage report
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: fasthub:mjJWGD8UpgSgKawKa5OqMNlR
  email: false