image: Visual Studio 2017
clone_folder: C:\FastHub

environment:
  ANDROID_HOME: C:\\Android\\android-sdk

init:
  - cmd: appveyor DownloadFile "https://dl.google.com/android/repository/tools_r25.2.3-windows.zip" -FileName "C:\android-tools.zip"
  - cmd: 7z x "C:\android-tools.zip" -o"%ANDROID_HOME%" > nul

install:
  - cmd: 'echo   > C:/Users/appveyor/.android/repositories.cfg'
  - ps: 'echo "y" | & C:/Android/android-sdk/tools/bin/sdkmanager.bat "platform-tools" --channel=2'
  - ps: 'echo "y" | & C:/Android/android-sdk/tools/bin/sdkmanager.bat "extras;android;m2repository" --channel=2'
  - ps: 'echo "y" | & C:/Android/android-sdk/tools/bin/sdkmanager.bat "extras;google;m2repository" --channel=2'
  - ps: 'echo "y" | & C:/Android/android-sdk/tools/bin/sdkmanager.bat "build-tools;26.0.0-rc2" --channel=2'
  - ps: 'echo "y" | & C:/Android/android-sdk/tools/bin/sdkmanager.bat "platforms;android-26" --channel=2'

build_script:
  - cmd: gradlew clean assembleDebug

test: off

artifacts:
- path: \app\build\outputs\apk
  name: APKs

deploy: off