image: Visual Studio 2017
clone_folder: C:\FH

environment:
  ANDROID_HOME: C:\\Android\\android-sdk

init:
  - cmd: appveyor DownloadFile "https://dl.google.com/android/repository/tools_r25.2.5-windows.zip" -FileName "C:\android-tools.zip"
  - cmd: 7z x "C:\android-tools.zip" -o"%ANDROID_HOME%" > nul

install:
  - cmd: 'echo   > C:/Users/appveyor/.android/repositories.cfg'
  - ps: |
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        Write-Host "PR detected. Installing C# Script Engine and doing translations check:"
        cinst cs-script
        cscs
        cscs -ac:2 -nl C:\FH\.github\check_translations.cs
      }
      Write-Host "Installing Android packages:"
      $pkgs = '"platform-tools"', '"extras;android;m2repository"', '"extras;google;m2repository"', '"build-tools;26.0.0"', '"platforms;android-25"'
      foreach ($pkg in $pkgs) {
        Write-Host "Installing ${pkg}:"
        echo "y" | & C:/Android/android-sdk/tools/bin/sdkmanager.bat ${pkg}
      }

build_script:
  - cmd: gradlew clean assembleDebug --stacktrace

after_build:
  - cmd: RENAME C:\FH\app\build\outputs\apk\debug\app-debug.apk fasthub-debug-%APPVEYOR_BUILD_VERSION%.apk

test: off

artifacts:
- path: \app\build\outputs\apk\debug\fasthub-debug-%APPVEYOR_BUILD_VERSION%.apk

deploy: off

notifications:
- provider: GitHubPullRequest
  template: ':x: [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})  <br>  <br>**Message(s):**  <br>{{#jobs}}{{#messages}}<br>{{message}}<br>{{/messages}}{{/jobs}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false